### ISSUE TITLE
Couldn't load shared library 'libjamepadarm64.dylib'

### ISSUE THREAD

**Issue by bladecoder** [libgdx/gdx-controllers#19]
The last release doesn't work in macos with the new arm processors.

The latest version of Jamepad includes the library for macos arm, so to fix this error, we only have to update the Jamepad dependency to **2.0.14.2**.

This is the error:

````
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Error creating controller manager: com.badlogic.gdx.controllers.desktop.JamepadControllerManager
        at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:119)
        at com.badlogic.gdx.controllers.Controllers.getControllers(Controllers.java:48)
        at com.bladecoder.engine.ui.UI.<init>(UI.java:78)
        at com.bladecoder.engine.BladeEngine.loadGame(BladeEngine.java:101)
        at com.bladecoder.engine.BladeEngine.create(BladeEngine.java:123)
        at com.bladecoder.engine.DesktopLauncher.create(DesktopLauncher.java:147)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:190)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:164)
        at com.bladecoder.engine.DesktopLauncher.run(DesktopLauncher.java:60)
        at com.bladecoder.engine.DesktopLauncher.main(DesktopLauncher.java:160)
Caused by: com.badlogic.gdx.utils.SharedLibraryLoadRuntimeException: Couldn't load shared library 'libjamepadarm64.dylib' for target: Mac OS X, 64-bit
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:128)
        at com.studiohartman.jamepad.ControllerManager.<init>(ControllerManager.java:66)
````

**Comment by MrStahlfelge** [comment]
You can update in your project, no need to push a gdx-controllers update.

**Comment by benjamin-heasly** [comment]
Thanks, this was helpful for me!

FWIW, here's how I did it in my libGDX project top-level `build.gradle`:
```
allprojects {

    // etc...

    dependencies {
        constraints {
            implementation("com.badlogicgames.jamepad:jamepad:$jamepadVersion") {
                because("Default jamepad version 2.0.14.1 is missing macOS arm64 binaries.")
            }
        }
    }

    // etc...

}
```

**Comment by ollyde** [comment]
I have the following

```
    dependencies {
        constraints {
            implementation("com.badlogicgames.jamepad:jamepad:2.26.5.0") {
                because("Default jamepad version 2.26.5.0 is missing macOS arm64 binaries.")
            }
        }
    }
```

I get the error 
`> Could not find method implementation() for arguments [com.badlogicgames.jamepad:jamepad:2.0.14.1, build_ejt9nlilfjibwbx8o7xtqyixl$_run_closure1$_closure8$_closure10$_closure11@c16df61] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyConstraintHandler.`

Any ideas?
