### ISSUE TITLE
OS X dyld: lazy symbol binding failed

### ISSUE THREAD

**Issue by tomcashman** [libgdx/gdx-controllers#5]
Getting the following exception when running on Mac OS X 10.13.6

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/6t/wtv2jc85473g4fq8023tpr7r0000gn/T/libgdxthomas/a2d22f08/libjamepad64.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/6t/wtv2jc85473g4fq8023tpr7r0000gn/T/libgdxthomas/a2d22f08/libjamepad64.dylib
  Expected in: /usr/lib/libSystem.B.dylib
```

However, when I checked in that folder, the file is there:

```
libjamepad64.dylib
```

Seems like its due to Github Actions running on Mac OS latest according to [this issue with a similar error](https://github.com/nodegui/nodegui/issues/391).

**Comment by MrStahlfelge** [comment]
Does the problem persist if you raise the jamepad version to 2.0.14.0?

I unfortunately only have the latest MacOS to test with.

**Comment by tomcashman** [comment]
2.0.14.0 works but 2.0.14.1 causes the following crash:

```
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Error creating controller manager: com.badlogic.gdx.controllers.desktop.JamepadControllerManager
        at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:110)
        at com.badlogic.gdx.controllers.Controllers.addListener(Controllers.java:56)
        ...
Caused by: java.lang.NoSuchMethodError: com.studiohartman.jamepad.ControllerManager.<init>(ILjava/lang/String;)V
        at com.badlogic.gdx.controllers.desktop.JamepadControllerManager.<init>(JamepadControllerManager.java:28)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at com.badlogic.gdx.utils.reflect.ClassReflection.newInstance(ClassReflection.java:93)
        at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:108)
        ... 8 more
```

**Comment by MrStahlfelge** [comment]
Hi,
Thanks for coming back. So 2.0.14.0 is it to use for Mac.

The crash with 2.0.14.1 is to be expected. 2.0.14.1 is not compatible with the current gdx-controllers release version (see [compatibility](https://github.com/libgdx/gdx-controllers/wiki/Compatibility) guide). Latest snapshot is adapted.

**Comment by MrStahlfelge** [comment]
Okay, I think we can close this then:

* I've added a hint to the changelog of Jamepad 2.0.14.0 release that this version works on older MacOS versions
* linked the releases page from the compatibility guide here
* 2.0.14.1 is already used in gdx-controllers snapshot, so won't be concerned by this issue
