### ISSUE TITLE
Getting ArrayIndexOutOfBoundsException from ControllerManager.java

### ISSUE THREAD

**Issue by Agueliethun** [libgdx/gdx-controllers#8]
I'm using the current version of gdx-controllers (2.1.0) and trying to use this library. When using a gamecube splitter adapter (USB to four gamecube ports) and a pro controller connected wirelessly, I get the following stack trace. I switched over to sdl2gdx and the problem went away, but then realized I wanted the sweet sweet functionality of controller.getMapping(), so here I am again. Right now I'm just getting around it by not using the gamecube splitter, but this is probably something to look at.

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Error creating controller manager: com.badlogic.gdx.controllers.desktop.JamepadControllerManager
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:110)
	at com.badlogic.gdx.controllers.Controllers.getControllers(Controllers.java:48)
	at com.agueliethun.vs2018.ui.MainMenu.initControllers(MainMenu.java:193)
	at com.agueliethun.vs2018.ui.MainMenu.<init>(MainMenu.java:61)
	at com.agueliethun.vs2018.ui.VillainSimulator.create(VillainSimulator.java:29)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:150)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at com.studiohartman.jamepad.ControllerManager.getControllerIndex(ControllerManager.java:236)
	at com.badlogic.gdx.controllers.desktop.support.JamepadControllerMonitor.checkForNewControllers(JamepadControllerMonitor.java:33)
	at com.badlogic.gdx.controllers.desktop.support.JamepadControllerMonitor.run(JamepadControllerMonitor.java:24)
	at com.badlogic.gdx.controllers.desktop.JamepadControllerManager.<init>(JamepadControllerManager.java:32)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404)
	at java.base/java.lang.Class.newInstance(Class.java:590)
	at com.badlogic.gdx.utils.reflect.ClassReflection.newInstance(ClassReflection.java:93)
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:108)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4

**Comment by MrStahlfelge** [comment]
Hi, you can assign a JamepadConfiguration to JamepadControllerManager before accessing the controllers the first time. Set the max exptected controllers to a higher level if you need it:

		Configuration jamepadConfiguration = new Configuration();
		jamepadConfiguration.maxNumControllers = 10;
		JamepadControllerManager.jamepadConfiguration = jamepadConfiguration;

This should help.

**Comment by MrStahlfelge** [comment]
BTW are you sure you are already on 2.1.0? Crash is already fixed by c166fa4728452927c63e46defdadcd4fefa07c58

**Comment by Agueliethun** [comment]
Ah, yeah it looks like I'm on version 2.0.1 rather than 2.1.0

**Comment by Agueliethun** [comment]
This was the issue - working fine now
